### ISSUE TITLE
Add download button on submitted charts page

### ISSUE THREAD

**Issue by nabinhait** [frappe/chart_of_accounts_builder#24]
The button will be visible only after successful submission of the charts, to ensure the contribution.

**Comment by robert1112** [comment]
Hi @nabinhait  Download link is not working. There is no response at all. Can you have a look? Thanks.

**Comment by nabinhait** [comment]
It is working for me. Which chart are you trying to download? Is there any error message in the browser's error console?

**Comment by robert1112** [comment]
France - Plan Comptable Général-6 
I just randomly pick one and there is no error message at all.

**Comment by robert1112** [comment]
I found error on console. Here is the screenshot. 
https://tppr.me/o5uPB

**Comment by nabinhait** [comment]
I can now replicate the download issue on https://charts.erpnext.com/chart?company=France%20-%20Plan%20Comptable%20G%C3%A9n%C3%A9ral-6&forked=1&submitted=1

I will fix it

**Comment by robert1112** [comment]
Thank you. And maybe add a simple tutorial about how to using the download file? It will help ppl decide to contribute on your platform instead of creating locally if they know they can use the contribution also. Thanks for your prompt support.

**Comment by nabinhait** [comment]
Sure, I will add a tutorial about it.

**Comment by nabinhait** [comment]
Fixed the downloading issue and added help docs.

**Comment by robert1112** [comment]
Forking works but dowload is not working. I still see the 404 error on my side.

**Comment by nabinhait** [comment]
It is working from here. Try in different browser. It can take some time, please wait 20-30 secs after clicking download button.

**Comment by robert1112** [comment]
Hi It works on Opera but no Safari. I saw the warning on Opera
"Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/."
Is it because this function is already deprecated on Safari? Thanks.
